version: '3.8'

services:
  # 개발용 서비스
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      platforms:
        - linux/arm64
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: bun run dev
    restart: unless-stopped

  # 프로덕션용 서비스
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      platforms:
        - linux/arm64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge