name: Deploy to EC2

on:
  push:
    branches: [release/20250726]
  pull_request:
    branches: [release/20250726]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 컨테이너 중지 및 제거
            docker stop worldy-talky || true
            docker rm worldy-talky || true

            # GitHub Container Registry 로그인
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 새 이미지 pull
            docker pull ghcr.io/${{ github.repository }}:latest

            # 컨테이너 실행
            docker run -d \
              --name worldy-talky \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NODE_ENV=production \
              ghcr.io/${{ github.repository }}:latest

            # 사용하지 않는 이미지 정리
            docker image prune -f
